import com.mongodb.BasicDBObject;
import com.mongodb.MongoClient;
import com.mongodb.MongoClientURI;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import javax.swing.JOptionPane;
import org.bson.Document;
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernamefield = new javax.swing.JTextField();
        clearbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nicknamefield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pwdfield = new javax.swing.JPasswordField();
        backbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        registerbtn = new javax.swing.JButton();
        cfpwdfield = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 119, 190, 30));

        clearbtn.setText("Clear");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 329, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("ConfirmPassword : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 219, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Nickname :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 269, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Register");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 59, -1, -1));

        nicknamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(nicknamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 269, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Username   : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 119, -1, -1));
        getContentPane().add(pwdfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 169, 190, 30));

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 369, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Password    : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 169, -1, -1));

        registerbtn.setText("Register");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 329, -1, -1));
        getContentPane().add(cfpwdfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 219, 190, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Pictures\\f07980d6b7cdb5655e2d19cf4e0b52df.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamefieldActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        usernamefield.setText("");
        pwdfield.setText("");
        cfpwdfield.setText("");
        nicknamefield.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void nicknamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknamefieldActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        dispose();

    }//GEN-LAST:event_backbtnActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        RegisterDB regis = new RegisterDB();
        if(checkFieldnotnull() == false){
            if(regis.checkUserExists(usernamefield.getText())){
                JOptionPane.showMessageDialog(null, "Username นี้มีผู้ใช้แล้วกรุณากรอกใหม่");
                usernamefield.setText("");
            }
            if(nicknamefield.getText().length()<3||checkpwdandcfpwd()==false){
                JOptionPane.showMessageDialog(null, "กรุณาตั้ง Nicknameอย่างน้อย3ตัวอักษรและ กรุณาตรวจสอบPassword ให้ตรงกันและใส่อย่างน้อย6ตัว!");
                nicknamefield.setText("");
                cfpwdfield.setText("");
            }

            else{
                regis.addUser(usernamefield.getText(), pwdfield.getText(), nicknamefield.getText());
                int input = JOptionPane.showConfirmDialog(null, "Welcome, " + nicknamefield.getText());
                if(input == 0){
                    Register re = new Register();
                    re.dispose();
                }

            }
        }
        else{
            JOptionPane.showMessageDialog(null, "กรุณากรอก ข้อมูลให้ครบทุกช่อง");
        }

    }//GEN-LAST:event_registerbtnActionPerformed
    boolean checkFieldnotnull(){
        boolean flag = false;
        if(usernamefield.getText().equals("")|| pwdfield.getPassword().equals("")
           || nicknamefield.getText().equals("")||cfpwdfield.getPassword().equals("")){
            flag = true;
            return flag;
        } else
        return flag;
    }
    
    boolean checkpwdandcfpwd(){
        if(pwdfield.getText().equals(cfpwdfield.getText()))
            return true;
        if(pwdfield.getText().length()>=6)
            return true;
        return false;
    }
    public String tostring(){
        return pwdfield.getText();
    } 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JPasswordField cfpwdfield;
    private javax.swing.JButton clearbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField nicknamefield;
    private javax.swing.JPasswordField pwdfield;
    private javax.swing.JButton registerbtn;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
